[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.100"
dusk-bls12_381 = "0.14.2"
dusk-poseidon = "0.41.0"
getrandom = { version = "0.2.16", features = ["js"] }
primitive-types = "0.14.0"
wasm-bindgen = "0.2.103"
