use crate::bluesky::Scalar;
use crate::poseidon;
use crate::utils;
use ff::{Field, PrimeField};
use std::sync::LazyLock;

/// Computes all Merkle hashes of a vector of values up to the root.
///
/// `n` is the number of values and must be a power of two.
///
/// The full Merkle tree is stored inline in the `values` vector as follows:
///
///   * the first `n` elements are the values of the original vector,
///   * the next `n / 2` elements are the hashes of the second-last layer of the tree,
///   * the next `n / 4` elements are the hashes of the third-last layer of the tree,
///   * ...
///   * the last stored element is the Merkle root.
///
/// It's the caller's responsibility to ensure the `values` array has at least `n * 2 - 1` slots so
/// that the full tree can be stored.
///
/// Note that the Merkle root will be at index `(n - 1) * 2`.
fn merklify(values: &mut [Scalar], mut n: usize) {
    assert!(n.is_power_of_two());
    let mut i = 0;
    while n > 1 {
        let m = n / 2;
        for j in 0..m {
            values[i + n + j] = poseidon::hash_t3(&[values[i + j * 2], values[i + j * 2 + 1]]);
        }
        i += n;
        n = m;
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Commitment {
    roots: Vec<Scalar>,
}

/// A complete FRI opening proof.
#[derive(Debug, Clone)]
pub struct Proof {
    index: usize,
    // TODO
}

impl Proof {
    /// Returns the index of the opened value.
    pub fn index(&self) -> usize {
        self.index
    }
}

/// A FRI prover.
///
/// The struct contains the original committed vector, the Merkle tree built upon it, all folded
/// polynomials, and all Merkle trees of all folded polynomials. All scalars are laid out on a
/// single flat array.
///
/// Each Merkle tree is complete because the size of the bottom layer is always a power of 2, so we
/// store it inline using `2n` slots, with `n` being the size of the bottom layer. Note: a complete
/// binary tree with `n` leaves would normally require `2n-1` slots, but we pad all trees with an
/// empty slot to simplify the layout formula. This results in `log2(n)` unused slots in total,
/// which we deem acceptable.
///
/// The layout of a Merkle tree with `n` leaves is the one generated by the `merklify` function
/// above, plus an extra element for padding. Our Merkle trees are stored in the `values` array
/// sequentially as follows:
///
///   * the first tree is the main Merkle tree (`n` committed elements, `2n` used slots),
///   * the second tree is the one resulting from the first folding round (`n/2` leaves, `n` used
///     slots),
///   * the third tree is the one resulting from the second folding round (`n/4` leaves, `n/2` used
///     slots),
///
/// etc.
///
/// The total size of the `values` array is `4n-2`.
#[derive(Debug, Clone)]
pub struct Prover {
    values: Vec<Scalar>,
}

impl Prover {
    /// Runs a folding round over a Merkle tree with `n` leaves, resulting in a new Merkle tree with
    /// `n/2` leaves.
    ///
    /// The input Merkle tree must be stored at the beginning of the provided slice, so that the
    /// first `n` elements of the slice are the evaluations of the polynomial to fold.
    ///
    /// The root of the input Merkle tree is therefore located at index `(n - 1) * 2` and is used to
    /// generate the Fiat-Shamir challenge for the round.
    ///
    /// The output Merkle tree will be stored at offset `2n` and will take exactly `n` slots
    /// (including the final padding element). It's the caller's responsibility to ensure that
    /// `values` has enough space.
    fn fold(values: &mut [Scalar], n: usize) {
        assert!(n.is_power_of_two());

        static DST: LazyLock<Scalar> =
            LazyLock::new(|| utils::hash_to_scalar(b"libernet/fri2/challenge"));
        let alpha = poseidon::hash_t3(&[*DST, values[(n - 1) * 2]]);

        let k = n.trailing_zeros();
        let omega_inv = Scalar::ROOT_OF_UNITY_INV.pow_vartime([1u64 << (Scalar::S - k), 0, 0, 0]);

        let m = n / 2;
        let mut omega_inv_i = Scalar::ONE;
        for i in 0..m {
            let f_pos = values[i];
            let f_neg = values[i + m];
            values[2 * n + i] =
                (f_pos + f_neg + alpha * omega_inv_i * (f_pos - f_neg)) * Scalar::TWO_INV;
            omega_inv_i *= omega_inv;
        }

        merklify(&mut values[(2 * n)..(3 * n)], m);
    }

    /// Runs all folding passes by calling `fold` iteratively until the polynomial is folded into a
    /// single scalar.
    ///
    /// All generated Merkle trees are laid out across `values` as described above.
    fn fold_all(values: &mut [Scalar], n: usize) {
        let mut offset = 0usize;
        let mut m = n;
        while m > 1 {
            Self::fold(&mut values[offset..], m);
            offset += 2 * m;
            m /= 2;
        }
    }

    pub fn new(mut values: Vec<Scalar>) -> Self {
        let n = values.len().next_power_of_two();
        assert!(n <= 1usize << Scalar::S);
        values.resize(n * 4 - 2, Scalar::ZERO);
        merklify(&mut values[0..(2 * n)], n);
        Self::fold_all(&mut values, n);
        Self { values }
    }

    /// Returns the length of the original committed vector.
    pub fn length(&self) -> usize {
        (self.values.len() + 2) / 4
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::utils::parse_scalar;

    #[test]
    fn test_merklify_one() {
        let mut values = vec![12.into()];
        merklify(&mut values, 1);
        assert_eq!(values, vec![12.into()]);
    }

    #[test]
    fn test_merklify_two() {
        let mut values = vec![34.into(), 56.into()];
        values.resize(3, 0.into());
        merklify(&mut values, 2);
        assert_eq!(
            values,
            vec![
                34.into(),
                56.into(),
                parse_scalar("0x5ec03322128c00fc47cb817c548a0dd60d1f10817b4cefe8ad1de3ea4504a552")
            ]
        );
    }

    #[test]
    fn test_merklify_four() {
        let mut values = vec![78.into(), 90.into(), 12.into(), 34.into()];
        values.resize(7, 0.into());
        merklify(&mut values, 4);
        assert_eq!(
            values,
            vec![
                78.into(),
                90.into(),
                12.into(),
                34.into(),
                parse_scalar("0x64276ccf57e84d0b2cbf42907160074c5d3db75ff85bd92d78580624c8cd8260"),
                parse_scalar("0x165e74be18ef4be6de5e232cd3480dcc38176807ac918b904576964612c5b6de"),
                parse_scalar("0x1b207cff4c6c97c46c0b950b7524dae299cf3b48d766f0e5990a63fc378cba29"),
            ]
        );
    }

    // TODO
}
